#!/bin/bash
set -e

PAM_FILE="/etc/pam.d/cockpit"
PAM_LINE="auth       required pam_google_authenticator.so nullok"

if [ -w "$PAM_FILE" ]; then
    if ! grep -Fxq "$PAM_LINE" "$PAM_FILE"; then
        echo "$PAM_LINE" >> "$PAM_FILE"
    fi
fi

exit 0
