#!/bin/bash
set -e

PAM_FILE="/etc/pam.d/cockpit"
PAM_LINE="auth       required pam_google_authenticator.so nullok"

# Remove the PAM line if it exists
if [ -f "$PAM_FILE" ]; then
    grep -Fxq "$PAM_LINE" "$PAM_FILE" && sed -i "\|$PAM_LINE|d" "$PAM_FILE"
fi
